package regular.service.com.utils;

public interface MessageConstants {
    String USER_ALREADY_REGISTERED = "USER_ALREADY_REGISTERED";
    String SHOULD_NOT_BE_EMPTY = "SHOULD_NOT_BE_EMPTY";
    String USER_NOT_FOUND_OR_DISABLED = "USER_NOT_FOUND_OR_DISABLED";
    String LOGIN_OR_PASSWORD_ERROR = "LOGIN_OR_PASSWORD_ERROR";
    String CONFIRMATION_CODE_INCORRECT = "CONFIRMATION_CODE_INCORRECT";
    String BAD_REQUEST = "BAD_REQUEST";
    String ROLE_NOT_FOUND = "ROLE_NOT_FOUND";
    String SUCCESSFULLY_STUDENT_ADDED = "SUCCESSFULLY_STUDENT_ADDED";
    String SMS_CODE_WITH_TEXT = "SMS_CODE_WITH_TEXT";
    String VERIFICATION_CODE_WITH_TEXT_EMAIL_TWO_STEP_VERIFICATION = "VERIFICATION_CODE_WITH_TEXT_EMAIL_TWO_STEP_VERIFICATION";
    String VERIFICATION_CODE_WITH_TEXT_EMAIL = "VERIFICATION_CODE_WITH_TEXT_EMAIL";
    String SMS_CODE_MUST_BE_BETWEEN = "SMS_CODE_MUST_BE_BETWEEN";
    String PASSWORDS_AND_PRE_PASSWORD_NOT_EQUAL = "PASSWORDS_AND_PRE_PASSWORD_NOT_EQUAL";
    String VERIFICATION_CODE_SENT_TO_PHONE_NUMBER = "VERIFICATION_CODE_SENT_TO_PHONE_NUMBER";
    String VERIFICATION_CODE_SENT_TO_EMAIL = "VERIFICATION_CODE_SENT_TO_EMAIL";
    String PHONE_NUMBER_SENT_TO_EMAIL = "PHONE_NUMBER_SENT_TO_EMAIL";
    String USER_NOT_FOUND = "USER_NOT_FOUND";
    String PASSWORD_SHOULD_NOT_BE_EMPTY = "PASSWORD_SHOULD_NOT_BE_EMPTY";
    String PASSWORD_ERROR = "PASSWORD_ERROR";
    String TWO_PASSWORD_SHOULD_NOT_BE_EMPTY = "TWO_PASSWORD_SHOULD_NOT_BE_EMPTY";
    String TWO_PASSWORD_ERROR = "TWO_PASSWORD_ERROR";
    String PASSWORD_AND_HINT_EQUAL = "PASSWORD_AND_HINT_EQUAL";
}
